import type { Profile } from "../shared/types.ts";
import { nativeProvider } from "./agent-config.ts";

export function openCodePlugin(
  profile: Profile,
  socket: string,
  port: number,
): string {
  const provider = nativeProvider(profile);
  const base = `http://127.0.0.1:${port}/p/${profile.slug}/v1`;
  return `// Generated by nonstopvibin. Credentials are requested for discovery and inference.
import http from "node:http";
const providerID = ${JSON.stringify(provider)};
const baseURL = ${JSON.stringify(base)};
function credential() {
  return new Promise((resolve, reject) => {
    const failure = () => new Error("Open nonstopvibin and start ${profile.slug}. If its port changed, reconnect OpenCode in the app.");
    const request = http.get({
      socketPath: ${JSON.stringify(socket)},
      path: ${JSON.stringify(`/profiles/${profile.id}`)},
      headers: { Host: "localhost" },
    }, (response) => {
      let body = "";
      response.setEncoding("utf8");
      response.on("data", (chunk) => {
        body += chunk;
        if (body.length > 128) request.destroy(failure());
      });
      response.on("error", () => reject(failure()));
      response.on("end", () => {
        const match = /^nv_[A-Za-z0-9_-]{43}\\n([0-9]{1,5})$/.exec(body);
        if (response.statusCode !== 200 || !match || match[1] !== ${JSON.stringify(String(port))}) reject(failure());
        else resolve(body.split("\\n")[0]);
      });
    });
    const timer = setTimeout(() => request.destroy(failure()), 5000);
    request.on("close", () => clearTimeout(timer));
    request.on("error", () => reject(failure()));
  });
}
export default async function () {
  return {
    async config(config) {
      config.provider ??= {};
      if (Object.hasOwn(config.provider, providerID)) throw new Error("Remove the conflicting nonstopvibin provider from OpenCode config, then restart OpenCode.");
      const key = await credential();
      const response = await fetch(baseURL + "/models?nonstopvibin=opencode", {
        headers: { Authorization: "Bearer " + key }, redirect: "error", signal: AbortSignal.timeout(30000)
      });
      if (!response.ok) throw new Error("Could not refresh nonstopvibin models. Open Connect agents and check this profile's catalog.");
      const { models } = await response.json();
      if (!Array.isArray(models) || !models.length) throw new Error("The nonstopvibin catalog is empty.");
      config.provider[providerID] = {
        npm: "@ai-sdk/openai-compatible",
        name: ${JSON.stringify(`nonstopvibin · ${profile.name}`)},
        models: Object.fromEntries(models.map(({ id, ...model }) => [id, model])),
        options: {
          baseURL,
          async fetch(input, init) {
            const url = new URL(input instanceof Request ? input.url : input);
            if (url.href !== baseURL + "/chat/completions") throw new Error("nonstopvibin refused a request outside this profile's endpoint.");
            const key = await credential();
            const headers = new Headers(init?.headers ?? (input instanceof Request ? input.headers : undefined));
            headers.set("Authorization", "Bearer " + key);
            const response = await fetch(input, { ...init, headers, redirect: "error" });
            if (response.status >= 300 && response.status < 400) throw new Error("nonstopvibin refused a redirect.");
            return response;
          },
        },
      };
    },
    "experimental.provider.small_model": async ({ provider }, output) => {
      if (provider.id === providerID) output.model = Object.values(provider.models)[0];
    },
    "chat.params": async ({ message, model }) => {
      if (message.model.providerID === providerID && model.providerID !== providerID) throw new Error("OpenCode's background model points outside this nonstopvibin profile. Remove its small_model or agent model override, then restart OpenCode.");
    },
  };
}
`;
}
